spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_tracker
    username: library
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
